### ISSUE TITLE
Delegate and expression errors

### ISSUE THREAD

**Issue by claydegruchy** [johnsoncodehk/unity-ui-controller#1]
I seem to be getting two errors on load with Unity 5.5.1f1 personal:
`Assets/UIController/Scripts/UIControllerStateMachine.cs(23,58): error CS1660: Cannot convert 'lambda expression' to non-delegate type 'Action'
`

and 

`Assets/UIController/Scripts/UIControllerStateMachine.cs(46,3): error CS0119: Expression denotes a 'variable', where a 'method group' was expected
`

Any ideas?

**Comment by johnsoncodehk** [comment]
https://github.com/johnsoncodehk/unity-uicontroller/pull/2

I can't get your error in Unity 5.5.1(OSX), but I try to fix, please tall me if working or not, I will update to Asset Store in next version.

[UIControllerStateMachine.cs](https://github.com/johnsoncodehk/unity-uicontroller/blob/3a9cbeadb67a0a56a768f521e311f9ad08510b22/Assets/UIController/Scripts/UIControllerStateMachine.cs)

**Comment by claydegruchy** [comment]
Perfect, this works great. I don't have anything else funky going on which would be interrupting the original (that I know of) but this definitely fixed my issue.

Thanks for the help.
