### ISSUE TITLE
Set the initial state

### ISSUE THREAD

**Issue by mschakulat** [johnsoncodehk/unity-ui-controller#3]
Thank you for this great plugin.
One question: Is it possible to set the initial state somehow? The problem is, that the initial state seems always to be the "show" animation. So if i start the scene, all elements will slide/fade in. I can't figure out how to fix it.

Thanks in advance
Micha

**Comment by johnsoncodehk** [comment]
If the component onHideAction is Disable or Destory, you can just let the GameObject inactive on scene.

You can see the "Popups" and "CSS" Example in Assets/UIController/Examples.unitypackage, these also is initial Hide state.

Thanks for your issue :)

**Comment by johnsoncodehk** [comment]
In 2.0 version, you can set the value of showOnAwake.
If enabled, show animation will start playing when GameObject enable.
